Update korean-checker

diff --git a/.github/workflows/korean-checker.yaml b/.github/workflows/korean-checker.yaml
--- a/.github/workflows/korean-checker.yaml
+++ b/.github/workflows/korean-checker.yaml
@@ -11,6 +11,7 @@ on:
 # Environment variables
 env:
   OUTPUT_DIR: "./output"
+  OUTPUT_FILE: "korean-check-results.md"
 
 jobs:
   check-if-Korean-is-included:
@@ -51,9 +52,9 @@ jobs:
           echo "(DEBUG) github.head_ref: ${{github.head_ref}}"
           echo "(DEBUG) github.base_ref: ${{github.base_ref}}"
           #####################################################
-
+          
           temp_output="temp.md"
-          output="${OUTPUT_DIR}/korean-check-results.md"
+          OUTPUT="${OUTPUT_DIR}/{OUTPUT_FILE}"
           
           # Get changed files in the PR
           files=$(git diff --name-only ${BASE_BRANCH}...${PR_BRANCH} | grep '\.go$')
@@ -86,45 +87,37 @@ jobs:
             fi          
           done
           
-          # Check if the file exists
+          # Output the results to check if Korean exists
+          # Check if the temp_output exists and has content
           if [ -s "$temp_output" ]; then
-            # Trim
+            
+            # Trim before checking if the file has content
             trimmed_temp_outputs=$(cat "$temp_output" | xargs)
             echo "(DEBUG) Trimmed temp_output:"
             echo "$trimmed_temp_outputs"
               
             if [ -n "$trimmed_temp_outputs" ]; then
               echo "(DEBUG) Korean content detected."
-              echo "### The result to check if Korean is included" > $output
-              echo "All output of print and log must be written in English :wink:" >> $output
-              echo "Please, check and correct the following" >> $output 
-              cat "$temp_output" >> "$output"
-              echo "KOREAN_EXISTS=true" >> $GITHUB_OUTPUT
+              cat "$temp_output" > "$OUTPUT"
+              # echo "KOREAN_EXISTS=true" >> $GITHUB_OUTPUT
             else
               echo "(DEBUG) No Korean content detected."
-              echo "KOREAN_EXISTS=false" >> $GITHUB_OUTPUT
+              # echo "KOREAN_EXISTS=false" >> $GITHUB_OUTPUT
             fi
-          fi
-          
-          # # Check if the file exists
-          # if [ -s "$output" ]; then
-          #   # Display output path
-          #   echo "[(Debug) Results saved in $output]"
-          #   cat "$output"
-          # fi
+          fi          
           
       - name: Upload Korean check results
-        if: steps.check-korean.outputs.KOREAN_EXISTS == 'true'
+        # if: steps.check-korean.outputs.KOREAN_EXISTS == 'true'
         uses: actions/upload-artifact@v4
         with:
           name: results-to-check-korean
           path: ${{ env.OUTPUT_DIR }}
 
-      - name: Fail on Korean Content
-        if: steps.check-korean.outputs.KOREAN_EXISTS == 'true'
-        run: |
-          echo "Korean content detected. Failing the workflow on purpose."
-          exit 1
+      # - name: Fail on Korean Content
+      #   if: steps.check-korean.outputs.KOREAN_EXISTS == 'true'
+      #   run: |
+      #     echo "Korean content detected. Failing the workflow on purpose."
+      #     exit 1
 
 # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
 # https://github.com/actions/upload-artifact
